"""errors and recoveries

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-16 09:58:54.671518

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "errors",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("recoverable", sa.Boolean(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("errors", schema=None) as batch_op:
        batch_op.create_index("ix_errors_resolved", ["resolved"], unique=False)
        batch_op.create_index("ix_errors_run_id", ["run_id"], unique=False)

    op.create_table(
        "recoveries",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("error_id", sa.Text(), nullable=True),
        sa.Column("start_event_id", sa.Integer(), nullable=True),
        sa.Column("result_event_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("outcome_json", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["error_id"], ["errors.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["result_event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["start_event_id"], ["events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recoveries", schema=None) as batch_op:
        batch_op.create_index("ix_recoveries_error_id", ["error_id"], unique=False)
        batch_op.create_index("ix_recoveries_run_id", ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recoveries", schema=None) as batch_op:
        batch_op.drop_index("ix_recoveries_run_id")
        batch_op.drop_index("ix_recoveries_error_id")

    op.drop_table("recoveries")
    with op.batch_alter_table("errors", schema=None) as batch_op:
        batch_op.drop_index("ix_errors_run_id")
        batch_op.drop_index("ix_errors_resolved")

    op.drop_table("errors")
    # ### end Alembic commands ###
