"""add the verifications table

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-16 11:02:26.026149

A plain additive revision: one new table, no change to ``runs``, ``events``,
``errors`` or ``recoveries``, so an existing database is upgraded in place with no
data movement. (Unlike ``0001``, this revision needs no existence guard: the table
it creates could not have existed before it did.)

``verifications.required`` is a real column rather than something derived from the
verifier's name, because "which checks does a verified success depend on?" must
stay answerable from stored data even after a verifier's defaults change.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verifications",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("verifier_type", sa.Text(), nullable=False),
        sa.Column("verifier_name", sa.Text(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("verifications", schema=None) as batch_op:
        batch_op.create_index("ix_verifications_run_id", ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verifications", schema=None) as batch_op:
        batch_op.drop_index("ix_verifications_run_id")

    op.drop_table("verifications")
    # ### end Alembic commands ###
