"""experiences and experience_sources

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-16 12:01:46.427957

Additive: two new tables, no change to anything Milestone 1-4 created, so an
existing store is upgraded in place with no data movement.

Deviations from the schema in the design document, all deliberate:

* ``kind`` -- the three experience kinds need to be queryable, not inferred from
  text (round-5 brief section 3);
* ``generalizable`` and ``outcome_verified`` -- required by sections 11 and 23-24;
* ``dedup_key`` -- a normalised fingerprint of (kind, domain, title, problem), used
  for deterministic duplicate detection (section 39). It is indexed but **not**
  unique: the key is a normalised string, and an over-aggressive normalisation must
  never be able to reject a legitimate experience. Merging is an application-level
  decision (D-035);
* ``reuse_count`` / ``success_count`` / ``failure_count`` are **absent**. They are
  outputs of ``experience_usage``, which does not exist yet; three counters nothing
  increments would read as "never reused" (D-037).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiences",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("symptoms_json", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("solution", sa.Text(), nullable=True),
        sa.Column("failed_attempts_json", sa.Text(), nullable=True),
        sa.Column("workflow_json", sa.Text(), nullable=True),
        sa.Column("avoid_json", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("generalizable", sa.Boolean(), nullable=False),
        sa.Column("outcome_verified", sa.Boolean(), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiences", schema=None) as batch_op:
        batch_op.create_index("ix_experiences_dedup_key", ["dedup_key"], unique=False)
        batch_op.create_index("ix_experiences_kind", ["kind"], unique=False)
        batch_op.create_index("ix_experiences_status", ["status"], unique=False)

    op.create_table(
        "experience_sources",
        sa.Column("experience_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["experience_id"], ["experiences.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("experience_id", "run_id"),
    )
    with op.batch_alter_table("experience_sources", schema=None) as batch_op:
        batch_op.create_index("ix_experience_sources_run_id", ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experience_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_experience_sources_run_id")

    op.drop_table("experience_sources")
    with op.batch_alter_table("experiences", schema=None) as batch_op:
        batch_op.drop_index("ix_experiences_status")
        batch_op.drop_index("ix_experiences_kind")
        batch_op.drop_index("ix_experiences_dedup_key")

    op.drop_table("experiences")
    # ### end Alembic commands ###
