/**
 * The bridge protocol: the only vocabulary the TypeScript plugin and the Python
 * bridge share.
 *
 * Why a protocol at all, rather than the plugin writing to AER directly: AER is
 * Python and DSH is Node. The boundary has to be explicit, and it has to be one
 * layer *below* `AgentExecutionEnvelope`, so the plugin can be tested without
 * Python and the Python side can be tested without DSH. Everything the plugin
 * learned from DSH crosses this boundary as JSON; nothing AER-specific is
 * decided on the TypeScript side.
 *
 * Framing is one JSON object per line in both directions (round-8.2 section 47).
 *
 * @module @aer/dsh-adapter/protocol
 */

/** Bumped when the shape of {@link BridgeRequest} / {@link BridgeResponse} changes. */
export const AER_BRIDGE_PROTOCOL_VERSION = 1;

/**
 * The operations the plugin may ask the bridge to perform.
 *
 * Deliberately small: a plugin that can call arbitrary AER code has no boundary.
 * Every operation maps to one Runtime API call on the Python side.
 */
export type BridgeOperation =
  /** A DSH session became known. Opens or resumes the AER session mapping. */
  | 'session.begin'
  /**
   * A turn began. Under turn granularity this is what opens the AER run, because a
   * turn is the unit that has an input, a trajectory and an outcome (section 12).
   */
  | 'turn.begin'
  /** One durable DSH event, already normalised. Idempotent by `external_event_id`. */
  | 'event.ingest'
  /** A turn ended with the reason DSH reported. Closes that turn's AER run. */
  | 'turn.end'
  /** The model is about to be called. Returns the context AER wants injected. */
  | 'experience.retrieve'
  /** DSH accepted the injected messages into the step. Records the injection. */
  | 'experience.injected'
  /** Liveness. Also the cheapest way for the probe to prove the bridge is alive. */
  | 'ping'
  /** Ordered shutdown: flush, then exit. */
  | 'shutdown';

/** One request from the plugin to the bridge. */
export interface BridgeRequest {
  readonly protocol: number;
  /** Correlates a response with its request. Generated by the plugin. */
  readonly request_id: string;
  readonly operation: BridgeOperation;
  readonly payload: Record<string, unknown>;
}

/** A structured bridge failure. `code` is stable; `message` is for a human. */
export interface BridgeError {
  readonly code: string;
  readonly message: string;
}

/** One response from the bridge to the plugin. */
export interface BridgeResponse {
  readonly protocol: number;
  readonly request_id: string;
  readonly ok: boolean;
  readonly result?: unknown;
  readonly error?: BridgeError;
}

// ---------------------------------------------------------------------------
// the normalised event
// ---------------------------------------------------------------------------

/**
 * The AER event types a DSH session event may translate to.
 *
 * The list is AER's, not DSH's: DSH has 56 durable event types and AER has eleven
 * business event types, and the mapping between them is this module's whole job. A
 * type that is not in this list is dropped *deliberately* rather than mapped into
 * something adjacent -- `approval/asked` is not a `TOOL_CALL`, and pretending it is
 * would put a call in the trace that the model never made.
 */
export type NormalizedEventType =
  | 'TOOL_CALL'
  | 'TOOL_RESULT'
  | 'ERROR'
  | 'MODEL_CALL'
  | 'MODEL_RESULT'
  | 'HUMAN_FEEDBACK';

/**
 * One durable DSH event, translated into AER's vocabulary but not yet into an
 * `AgentExecutionEnvelope`.
 *
 * The plugin produces these; the Python side turns them into envelopes and hands
 * them to `AdapterIngestor`. Keeping the pipeline one step short of the envelope on
 * this side means the plugin never needs to know about AER's ingestor, its session
 * handles, or its idempotency ledger.
 */
export interface NormalizedEnvelope {
  readonly event_type: NormalizedEventType;
  /**
   * `${sessionId}:${seq}`.
   *
   * DSH's `seq` is monotonic within a session and assigned by the durable log
   * itself, so the pair is a stable identity for the event rather than a hash of
   * its content (round-8.2 section 41). A retried delivery therefore collides with
   * the original, which is exactly what the AER ledger needs.
   */
  readonly external_event_id: string;
  readonly external_session_id: string;
  /** The DSH turn this event belongs to, as a string. Empty when the event has none. */
  readonly external_turn_id: string;
  /** DSH `seq`, the authoritative ordering key. Also the catch-up cursor. */
  readonly external_sequence: number;
  /** ISO-8601 derived from DSH's `time` (epoch milliseconds). */
  readonly external_timestamp: string;
  readonly payload: Record<string, unknown>;
  readonly metadata: Record<string, unknown>;
}

/** What DSH says a turn ended for, already reduced to an AER status by name. */
export type NormalizedTurnOutcome =
  /** The agent declared nothing; the loop stopped. AER closes it `INCONCLUSIVE`. */
  | 'INCONCLUSIVE'
  /** The agent declared the work failed. */
  | 'FAILED'
  /** The agent declared the work abandoned. */
  | 'ABORTED';

/** The session identity a turn's run is opened under. */
export interface NormalizedSession {
  readonly external_session_id: string;
  readonly cwd: string | null;
  readonly agent_preset: string | null;
  /** Present when this session was spawned as a subagent: its parent session. */
  readonly parent_session_id: string | null;
  readonly delegation_depth: number | null;
  /** `subagent` for a delegated session; null/absent when DSH did not say. */
  readonly origin: string | null;
  readonly created_at: string | null;
}

/** The provider route and model DSH resolved for a request. Never guessed (section 54). */
export interface NormalizedModel {
  readonly provider: string;
  readonly model: string;
}

/** What `turn.end` carries. */
export interface NormalizedTurnEnd {
  readonly session: NormalizedSession;
  readonly turn: number;
  /** The raw `TurnEndReasonMap` kind, kept so the report can show what DSH said. */
  readonly reason_kind: string;
  readonly outcome: NormalizedTurnOutcome;
  /** Present for `error`, `aborted` and any DSH-specific extension of the union. */
  readonly detail: Record<string, unknown>;
}

/** The bridge's answer to `experience.retrieve`. */
export interface RetrievalOffer {
  /** AER's handle for this retrieval, echoed back on `experience.injected`. */
  readonly retrieval_id: string;
  /** The exact model-facing text, already formatted by AER. Empty means nothing to inject. */
  readonly context_text: string;
  /** How many experiences were retrieved. Zero is a normal answer. */
  readonly experience_count: number;
}

/** One `tool/call` reduced to the facts AER records. */
export interface ToolCallFact {
  readonly call_id: string;
  readonly name: string;
  /** The model's raw JSON argument string, truncated and redacted on the Python side. */
  readonly arguments_json: string;
  readonly turn: number;
  readonly step: number;
}

/** One `tool/result` reduced to the facts AER records. */
export interface ToolResultFact {
  readonly call_id: string;
  readonly name: string;
  /** DSH's structured `isError`. Never inferred from the text (section 19). */
  readonly is_error: boolean;
  /** Present only when DSH attached a structured failure identity. */
  readonly error_name: string | null;
  readonly error_code: string | null;
  /** Model-facing output text, already reduced to a summary. */
  readonly output_summary: string;
  readonly turn: number;
  readonly step: number;
}
